// @ts-nocheck — #imports is only available inside a real Nuxt app
import { defineNuxtPlugin, useRuntimeConfig } from '#imports'
// @ts-expect-error — virtual template generated by the Nuxt module at build time
import { functionalOptions } from '#build/vue-command-palette-functional-options.mjs'
import { VCommandPalettePlugin } from '../../plugin'
import type { PaletteOptions } from '../../types'

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig()
  const serializableOptions = (config.public as Record<string, unknown>).vCommandPalette as
    | PaletteOptions
    | undefined

  // Function-valued options (search/onSearch/onOpen/onClose/onError/onHighlight)
  // come from the module's generated template (see "configFile" in
  // nuxt.config.ts), since they're stripped from runtimeConfig.public before
  // it ever reaches here (see FUNCTION_OPTION_KEYS in ../module.ts).
  nuxtApp.vueApp.use(VCommandPalettePlugin, {
    ...serializableOptions,
    ...(functionalOptions as Partial<PaletteOptions>),
  })
})
